[ localhost ]
127.0.0.1
[aws]
3.141.85.10 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file={{ private_key_content }}
[local]
10.0.2.6   ansible_connection=ssh ansible_user=root

