---
- name: install required packages
  apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - git
      - tar
      - unzip
      - gnupg-agent
      - software-properties-common
      - neovim
      - npm
    state: present

- name: fetch docker apt key debian
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  when: "ansible_distribution|string == 'Debian'"

- name: Add docker repository debian
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  when: "ansible_distribution|string == 'Debian'"

- name: fetch docker apt key ubuntu
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  when: "ansible_distribution|string == 'Ubuntu'"

- name: Add docker repository ubuntu
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: "ansible_distribution|string == 'Ubuntu'"

- name: Refresh cache
  apt:
    update_cache: yes

- name: Update distro
  apt:
    name: "*"
    state: latest

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.3/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: Check if rclone is installed
  package:
    name: rclone
    state: present
  check_mode: true
  register: rclone_check

- name: Installing rclone
  shell: curl https://rclone.org/install.sh | sudo bash
  when: not rclone_check.changed

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

