- name: Download backup
  get_url:
    url: "https://www.dropbox.com/s/513h35qbhvm3k4w/backup.tar.gz.gpg?dl=1"
    dest: /tmp/backup.tar.gz.gpg
    mode: 755

- name: Decrypt backup
  command: "gpg --pinentry-mode=loopback --yes --passphrase 'Vijay@29oct' -d -o /tmp/backup.tar.gz /tmp/backup.tar.gz.gpg"

- name: Unarchives backup
  ansible.builtin.unarchive:
    src: /tmp/backup.tar.gz
    dest: /
    remote_src: yes

- name: Cleanup task
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/backup.tar.gz
    - /tmp/backup.tar.gz.gpg
