- name: Download backup
  get_url:
    url: '{{ drop_link }}'
    dest: /tmp/backup.tar.gz.gpg
    mode: 755

- name: Decrypt backup
  command: "gpg --pinentry-mode=loopback --yes --passphrase '{{ gpg_pass }}' -d -o /tmp/backup.tar.gz /tmp/backup.tar.gz.gpg"

- name: Unarchives backup
  ansible.builtin.unarchive:
    src: /tmp/backup.tar.gz
    dest: /
    remote_src: yes

- name: Cleanup task
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/backup.tar.gz
    - /tmp/backup.tar.gz.gpg
