
- name: Service file creation for docker-compose.service
  tags: systemd
  copy:
    dest: /etc/systemd/system/docker-compose.service
    content: |
      [Unit]
      Description=Depoly Docker Compose Service
      Requires=docker.service
      After=docker.service
      [Service]
      Type=oneshot
      RemainAfterExit=true
      WorkingDirectory=/docker/compose
      ExecStart=/usr/local/bin/docker-compose up -d --remove-orphans
      ExecStop=/usr/local/bin/docker-compose down
      [Install]
      WantedBy=multi-user.target

- name: Service file creation for autoBackup.service
  tags: systemd
  copy:
    dest: /etc/systemd/system/autoBackup.service
    content: |
      [Unit]
      Description=Creating tar backup
      [Service]
      Type=oneshot
      #WorkingDirectory=/webbackup
      ExecStart=/bin/bash /docker/scripts/backup.sh
      [Install]
      WantedBy=multi-user.target

- name: Service timer creation for autoBackup.service
  tags: systemd
  copy:
    dest: /etc/systemd/system/autoBackup.timer
    content: |
      [Unit]
      Description=runs autoBackup.service
      [Timer]
      OnCalendar=*-*-* */12:00:00
      Persistent=true
      Unit=autoBackup.service
      [Install]
      WantedBy=timers.target

- name: Create a /var/log/rclone-backup if it does not exist
  ansible.builtin.file:
    path: /var/log/rclone-backup
    state: directory
    mode: '0755'

- name: Systemd service daemon_reload
  tags: systemd
  systemd:
    daemon_reload: yes

- name: Systemd service activation for docker-compose.service
  tags: systemd
  systemd:
      enabled: yes
      state: started
      name: docker-compose.service

- name: Systemd service activation for autoBackup.service
  tags: systemd
  systemd:
      enabled: yes
        #state: started
      name: autoBackup.service

- name: Systemd service activation for autoBackup.timer
  tags: systemd
  systemd:
      enabled: yes
      state: started
      name: autoBackup.timer

